### ISSUE TITLE
Text component not working in 0.4.0

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/kframe#20]

**Comment by kfarr** [comment]
`Uncaught (in promise) TypeError: paths[p].toShapes is not a function           aframe-text-component.js:350 ` 

Looks like three.js changed its font shape handling:
https://threejs.org/docs/?q=shapepath#Reference/Extras.Core/ShapePath

http://stackoverflow.com/questions/40064766/three-js-toshapes-moved-to-new-class-in-v81-how-to-access-it

**Comment by ngokevin** [comment]
Updated. three.js no longer uses typeface.js files, but typeface.json, meaning I had to now handle the XHR loading.

**Comment by edweena** [comment]
is this compiled into `dist`?

**Comment by ngokevin** [comment]
https://github.com/ngokevin/kframe/tree/master/components/text/dist
